Set up material UI && Integrate with Tailwind CSS
KanaryStack/aliascheck pull request #14
Opened 2022-07-06 16:43 UTC by RWambui

- Tailwind integration
- Material UI integration
- Tailwind injection order
- Breakpoints and global styles config

2022-07-06 17:24 UTC, Maxwell-ihiaso reviewed
- TailwindCSS implemented correctly 🕶
- MaterialUI implemented correctly 🎏
- Injection order set for Material UI to accept styles from TailwindCSS without conflict 🎈
- General housekeeping is done (Media Queries and global styles) 🎉

2022-07-06 17:26 UTC, rotimidokun requested changes
Added a few changes to be addressed. @RWambui

2022-07-06 17:26 UTC, rotimidokun commented on client/pages/index.tsx
> +// import Slider from '@mui/material/Slider';
Please remove comment @RWambui

2022-07-06 17:26 UTC, rotimidokun commented on client/pages/index.tsx
> +const Home: NextPage = () => {
```suggestion
const Home = () => {
```

@RWambui

2022-07-06 18:05 UTC, rotimidokun commented
All changes requested are implemented and PR is good to be merged. @Maxwell-ihiaso comment does a good job at describing what we have implemented @simplytunde

2022-07-06 18:22 UTC, simplytunde commented
> All changes requested are implemented and PR is good to be merged. @Maxwell-ihiaso comment does a good job at describing what we have implemented @simplytunde

Give approval once good to go

2022-07-10 10:01 UTC, rotimidokun approved these changes
All changes have been implemented now. Good to merge.

2022-07-10 10:44 UTC, merged